version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=future

  apache-local.app:
    image: ambientum/php:7.0-apache
    container_name: apache-local.app
    volumes:
      - .:/var/www/app/public
    ports:
      - "8090:8080"

  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
  